export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SHOUTBOX_FETCH_REQUEST = "SHOUTBOX_FETCH_REQUEST";
export const SHOUTBOX_FETCH_SUCCESS = "SHOUTBOX_FETCH_SUCCESS";
export const SHOUTBOX_FETCH_FAILURE = "SHOUTBOX_FETCH_FAILURE";

export const SHOUTBOX_FETCH_DELTA_REQUEST = "SHOUTBOX_FETCH_DELTA_REQUEST";
export const SHOUTBOX_FETCH_DELTA_SUCCESS = "SHOUTBOX_FETCH_DELTA_SUCCESS";

export const SHOUTBOX_SEND_SHOUT = "SHOUTBOX_SEND_SHOUT";
export const SHOUTBOX_REMOVE_SHOUT = "SHOUTBOX_REMOVE_SHOUT";

export const FORUM_QUOTE_POST = "FORUM_QUOTE_POST";
export const FORUM_EDIT_POST = "FORUM_EDIT_POST";

export const NOTIFICATIONS_CHECK_REQUEST = "NOTIFICATIONS_CHECK_REQUEST";
export const NOTIFICATIONS_CHECK_SUCCESS = "NOTIFICATIONS_CHECK_SUCCESS";